/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Restaurant_Example;

public class Restaurant {
   public static void main(String[] args) {      
      Kitchen kitchen = new Kitchen();

      Food burger = kitchen.getFood("Burger");
      burger.order();
 
      Food fries = kitchen.getFood("Fries");
      fries.order();
 
      Food pizza = kitchen.getFood("Pizza");
      pizza.order();

      Food salad = kitchen.getFood("Salad");
      salad.order();
   }
}